In [1]:
    import numpy as np
import pandas as pd
from sympy import sequence
from unicodedata import category

books = pd.read_csv("books_cleaned.csv")

In [2]:
    books["categories"].value_counts().reset_index().head(20)

                   categories  count
0                     Fiction   2111
1            Juvenile Fiction    390
2   Biography & Autobiography    311
3                     History    207
4          Literary Criticism    124
5                  Philosophy    117
6                    Religion    117
7     Comics & Graphic Novels    116
8                       Drama     86
9         Juvenile Nonfiction     57
10                    Science     56
11                     Poetry     51
12       Literary Collections     50
13       Business & Economics     49
14             Social Science     48
15            Performing Arts     40
16                    Cooking     35
17                 Psychology     33
18                     Travel     32
19        Body, Mind & Spirit     32

In [3]:
    books["categories"].value_counts().reset_index().query("count > 20")

                     categories  count
0                       Fiction   2111
1              Juvenile Fiction    390
2     Biography & Autobiography    311
3                       History    207
4            Literary Criticism    124
5                    Philosophy    117
6                      Religion    117
7       Comics & Graphic Novels    116
8                         Drama     86
9           Juvenile Nonfiction     57
10                      Science     56
11                       Poetry     51
12         Literary Collections     50
13         Business & Economics     49
14               Social Science     48
15              Performing Arts     40
16                      Cooking     35
17                   Psychology     33
18                       Travel     32
19          Body, Mind & Spirit     32
20                          Art     32
21            Political Science     30
22                    Self-Help     28
23             Health & Fitness     28
24                    Computers     28
25       Family & Relationships     27
26  Language Arts & Disciplines     23
27                        Humor     23

In [4]:
    books[books["categories"] == "Business & Economics"]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
89,9780060005696,0060005696,The Paradox of Choice,Barry Schwartz,Business & Economics,NaN,The author of The Battle for Human Nature expl...,2005.0,3.84,265.0,23734.0,The Paradox of Choice: Why More Is Less,9780060005696 The author of The Battle for Hum...
128,9780060521998,0060521996,The Innovator's Dilemma,Clayton M. Christensen,Business & Economics,http://books.google.com/books/content?id=qZxlD...,"In this revolutionary bestseller, Harvard prof...",2003.0,3.99,286.0,28568.0,The Innovator's Dilemma: The Revolutionary Boo...,9780060521998 In this revolutionary bestseller...
134,9780060529574,0060529571,The Big Bing,Stanley Bing,Business & Economics,http://books.google.com/books/content?id=Cb3Ml...,A corporate mole's-eye view of the society in ...,2006.0,3.08,368.0,26.0,"The Big Bing: Black Holes of Time Management, ...",9780060529574 A corporate mole's-eye view of t...
149,9780060566104,0060566108,Built to Last,Jim Collins;Jerry I. Porras,Business & Economics,http://books.google.com/books/content?id=lRNtH...,"""This is not a book about charismatic visionar...",2004.0,3.98,368.0,49529.0,Built to Last: Successful Habits of Visionary ...,"9780060566104 ""This is not a book about charis..."
444,9780071348270,0071348271,Mission Possible,Ken Blanchard;Terry Waghorn,Business & Economics,http://books.google.com/books/content?id=ofjQm...,Explains how to improve one's existing organiz...,1999.0,3.42,242.0,0.0,Mission Possible: Becoming a World Class Organ...,9780071348270 Explains how to improve one's ex...
445,9780071401944,0071401946,Crucial Conversations,Kerry Patterson;Joseph Grenny;Ron McMillan;Al ...,Business & Economics,http://books.google.com/books/content?id=PibJN...,The New York Times Bestseller! Learn how to ke...,2002.0,4.01,240.0,36535.0,Crucial Conversations: Tools for Talking when ...,9780071401944 The New York Times Bestseller! L...
547,9780131494848,0131494848,Leadership in Organizations,Gary A. Yukl,Business & Economics,http://books.google.com/books/content?id=WHyPQ...,This text provides the most comprehensive surv...,2006.0,3.68,542.0,55.0,Leadership in Organizations,9780131494848 This text provides the most comp...
852,9780143036975,0143036971,Bargaining for Advantage,G. Richard Shell,Business & Economics,http://books.google.com/books/content?id=zy5lD...,An authoritative guide to business negotiation...,2006.0,3.94,320.0,4406.0,Bargaining for Advantage: Negotiation Strategi...,9780143036975 An authoritative guide to busine...
861,9780143037835,0143037838,Let My People Go Surfing,Yvon Chouinard,Business & Economics,http://books.google.com/books/content?id=sjBAf...,The personal stories of the founder of Patagon...,2006.0,4.21,272.0,6467.0,Let My People Go Surfing: The Education of a R...,9780143037835 The personal stories of the foun...
865,9780143038825,0143038826,The White Man's Burden,William Easterly,Business & Economics,http://books.google.com/books/content?id=8SayN...,Argues that western foreign aid efforts have d...,2006.0,3.83,436.0,4317.0,The White Man's Burden: Why the West's Efforts...,9780143038825 Argues that western foreign aid ...
1072,9780231138703,0231138709,More Than You Know,Michael J. Mauboussin,Business & Economics,http://books.google.com/books/content?id=g6WlQ...,Mauboussin mines disciplines that are not norm...,2006.0,4.08,268.0,1238.0,More Than You Know: Finding Financial Wisdom i...,9780231138703 Mauboussin mines disciplines tha...
1097,9780262611336,0262611333,Pop Internationalism,Paul R. Krugman,Business & Economics,http://books.google.com/books/content?id=17Yrn...,"""Pop internationalists""--people who speak impr...",1997.0,3.67,221.0,307.0,Pop Internationalism,"9780262611336 ""Pop internationalists""--people ..."
1098,9780262611350,026261135X,"Development, Geography, and Economic Theory",Paul R. Krugman,Business & Economics,http://books.google.com/books/content?id=Pm_oA...,Why do certain ideas gain currency in economic...,1997.0,3.99,127.0,74.0,"Development, Geography, and Economic Theory",9780262611350 Why do certain ideas gain curren...
1103,9780273661948,0273661949,Marketing and the Bottom Line,Tim Ambler,Business & Economics,http://books.google.com/books/content?id=qeVE8...,Marketing and the bottom line sets out to chan...,2003.0,3.82,336.0,17.0,Marketing and the Bottom Line: The Marketing M...,9780273661948 Marketing and the bottom line se...
1104,9780273704744,0273704745,"Traders, Guns & Money",Satyajit Das,Business & Economics,http://books.google.com/books/content?id=QLw2s...,Derivatives. Warren Buffett once called them '...,2006.0,3.83,334.0,1398.0,"Traders, Guns & Money: Knowns and Unknowns in ...",9780273704744 Derivatives. Warren Buffett once...
1349,9780316172325,0316172324,Blink,Malcolm Gladwell,Business & Economics,http://books.google.com/books/content?id=00BYn...,The landmark book that has revolutionized the ...,2005.0,3.92,277.0,4089.0,Blink: The Power of Thinking Without Thinking,9780316172325 The landmark book that has revol...
1919,9780393323528,0393323528,Next: The Future Just Happened,Michael Lewis,Business & Economics,http://books.google.com/books/content?id=E0ZbI...,The author of Liar's Poker and The Next New Th...,2002.0,3.67,240.0,1271.0,Next: The Future Just Happened,9780393323528 The author of Liar's Poker and T...
1923,9780393324815,0393324818,Moneyball: The Art of Winning an Unfair Game,Michael Lewis,Business & Economics,http://books.google.com/books/content?id=3DnUC...,"Explains how Billy Beene, the general manager ...",2003.0,4.26,317.0,78308.0,Moneyball: The Art of Winning an Unfair Game,"9780393324815 Explains how Billy Beene, the ge..."
1924,9780393324860,0393324869,Naked Economics: Undressing the Dismal Science,Charles Wheelan,Business & Economics,http://books.google.com/books/content?id=-Tu1G...,Seeks to provide a genuinely engaging and comp...,2003.0,4.03,288.0,5703.0,Naked Economics: Undressing the Dismal Science,9780393324860 Seeks to provide a genuinely eng...
2269,9780446579780,0446579785,The Coming Economic Collapse,Stephen Leeb;Glen Strathy,Business & Economics,http://books.google.com/books/content?id=2TM6l...,"In this incredibly timely book,renowned econom...",2006.0,3.39,211.0,207.0,The Coming Economic Collapse: How You Can Thri...,"9780446579780 In this incredibly timely book,r..."
2467,9780465081431,0465081436,Applied Economics,Thomas Sowell,Business & Economics,http://books.google.com/books/content?id=2JqpP...,A companion volume to Basic Economics discusse...,2004.0,4.14,256.0,1466.0,Applied Economics: Thinking Beyond Stage One,9780465081431 A companion volume to Basic Econ...
2471,9780470038321,0470038322,Personal Finance For Dummies,Eric Tyson,Business & Economics,http://books.google.com/books/content?id=6-gnl...,Too many personal finance consultants offer fi...,2006.0,3.77,458.0,113.0,Personal Finance For Dummies,9780470038321 Too many personal finance consul...
2472,9780470043608,0470043601,Crash Proof,Peter D. Schiff;John Downes,Business & Economics,http://books.google.com/books/content?id=Wqe1N...,The economic tipping point for the United Stat...,2007.0,3.79,272.0,1066.0,Crash Proof: How to Profit From the Coming Eco...,9780470043608 The economic tipping point for t...
2473,9780470045299,0470045299,eBay For Dummies,Marsha Collier,Business & Economics,http://books.google.com/books/content?id=9VIhm...,Thinking about buying or selling items on eBay...,2006.0,3.50,386.0,102.0,eBay For Dummies,9780470045299 Thinking about buying or selling...
2476,9780471133124,0471133124,Extraordinary Popular Delusions and the Madnes...,Charles Mackay,Business & Economics,http://books.google.com/books/content?id=h23HW...,A study of crowd behavior includes two landmar...,1996.0,3.91,224.0,34.0,Extraordinary Popular Delusions and the Madnes...,9780471133124 A study of crowd behavior includ...
2490,9780471780939,0471780936,Power of An Hour,Dave Lakhani,Business & Economics,http://books.google.com/books/content?id=idPQN...,"Praise for The Power of an Hour ""The master at...",2006.0,3.31,205.0,163.0,Power of An Hour: Business and Life Mastery in...,9780471780939 Praise for The Power of an Hour ...
2884,9780609610572,0609610570,Execution,Larry Bossidy;Ram Charan;Charles Burck,Business & Economics,http://books.google.com/books/content?id=H-yLD...,An updated edition of the best-selling referen...,2002.0,3.86,278.0,21120.0,Execution: The Discipline of Getting Things Done,9780609610572 An updated edition of the best-s...
3018,9780671792800,0671792806,Principle Centered Leadership,Stephen R. Covey,Business & Economics,http://books.google.com/books/content?id=w4zCI...,The author invites business readers to center ...,1992.0,4.09,336.0,14453.0,Principle Centered Leadership,9780671792800 The author invites business read...
3078,9780679730613,0679730613,Hit Men,Fredric Dannen,Business & Economics,http://books.google.com/books/content?id=8vDWE...,An inside look at the multibillion-dollar musi...,1991.0,3.95,432.0,664.0,Hit Men: Power Brokers and Fast Money Inside t...,9780679730613 An inside look at the multibilli...
3178,9780688039691,0688039693,Leadership and the One Minute Manager,Ken Blanchard;Patricia Zigarmi;Drea Zigarmi,Business & Economics,http://books.google.com/books/content?id=a_k3u...,"In clear, simple terms Leadership and the One ...",1999.0,3.97,111.0,2445.0,Leadership and the One Minute Manager: Increas...,"9780688039691 In clear, simple terms Leadershi..."
3252,9780716799566,0716799561,Economics: European Edition,Paul Krugman;Robin Wells;Kathryn Graddy,Business & Economics,http://books.google.com/books/content?id=JgGyX...,Economics: European Edition is the ideal text ...,2007.0,3.95,1088.0,111.0,Economics: European Edition,9780716799566 Economics: European Edition is t...
3365,9780743297301,074329730X,The SPEED of Trust,Stephen R. Covey;Rebecca R. Merrill,Business & Economics,http://books.google.com/books/content?id=nQZnD...,The son of the author of the best-selling 7 Ha...,2006.0,3.98,384.0,16043.0,The SPEED of Trust: The One Thing that Changes...,9780743297301 The son of the author of the bes...
3488,9780750666008,0750666005,Brand New Justice,Simon Anholt,Business & Economics,http://books.google.com/books/content?id=MmahV...,Recently vilified as the prime dynamic driving...,2005.0,3.69,184.0,15.0,Brand New Justice: How Branding Places and Pro...,9780750666008 Recently vilified as the prime d...
3568,9780761512196,0761512195,Your First Year in Network Marketing,Mark Yarnell;Rene Reid Yarnell;Rene Yarnell,Business & Economics,http://books.google.com/books/content?id=c9jvr...,"Offers advice on dealing with rejection, recru...",1998.0,4.05,304.0,789.0,Your First Year in Network Marketing: Overcome...,9780761512196 Offers advice on dealing with re...
3680,9780767911795,0767911792,Conspiracy of Fools,Kurt Eichenwald,Business & Economics,http://books.google.com/books/content?id=yGqAP...,A study of the Enron scandal goes behind the s...,2005.0,4.22,784.0,4293.0,Conspiracy of Fools: A True Story,9780767911795 A study of the Enron scandal goe...
3689,9780767920742,0767920740,The Dictionary of Corporate Bullshit,Lois Beckwith,Business & Economics,http://books.google.com/books/content?id=NMYwm...,A caustic collection of workplace jargon and a...,2006.0,4.08,192.0,78.0,The Dictionary of Corporate Bullshit: An A to ...,9780767920742 A caustic collection of workplac...
3719,9780785260059,0785260056,The Power of One,John C. Maxwell;Thomas G. Addington,Business & Economics,http://books.google.com/books/content?id=L_FGs...,In this 30-day companion workbook to There's N...,2004.0,4.28,256.0,16.0,"The Power of One: One Person, One Rule, One Month",9780785260059 In this 30-day companion workboo...
3789,9780787960759,0787960756,The Five Dysfunctions of a Team,Patrick M. Lencioni,Business & Economics,http://books.google.com/books/content?id=dsN3C...,In The Five Dysfunctions of a Team Patrick Len...,2002.0,4.02,227.0,57971.0,The Five Dysfunctions of a Team: A Leadership ...,9780787960759 In The Five Dysfunctions of a Te...
3791,9780787968335,0787968331,The Leadership Challenge,James M. Kouzes;Barry Z. Posner,Business & Economics,http://books.google.com/books/content?id=a7Bzt...,"When it was initially written in 1987, few cou...",2003.0,4.04,458.0,865.0,The Leadership Challenge,9780787968335 When it was initially written in...
3793,9780787976385,0787976385,"Silos, Politics and Turf Wars",Patrick M. Lencioni,Business & Economics,http://books.google.com/books/content?id=P17HA...,"In yet another page-turner, New York Times bes...",2006.0,4.04,224.0,2419.0,"Silos, Politics and Turf Wars: A Leadership Fa...","9780787976385 In yet another page-turner, New ..."
3858,9780805063899,0805063897,Nickel and Dimed,Barbara Ehrenreich,Business & Economics,http://books.google.com/books/content?id=s642s...,The sharp social critic and author of Blood Ri...,2002.0,3.62,240.0,163279.0,Nickel and Dimed: On (Not) Getting By in America,9780805063899 The sharp social critic and auth...
4007,9780812975215,0812975219,Fooled By Randomness,Nassim Taleb,Business & Economics,http://books.google.com/books/content?id=4eLKm...,Contends that randomness and probability have ...,2005.0,4.05,368.0,37122.0,Fooled By Randomness: The Hidden Role Of Chanc...,9780812975215 Contends that randomness and pro...
4214,9780887309427,0887309429,Die Broke,Stephen Pollan;Mark Levine,Business & Economics,http://books.google.com/books/content?id=kPkkl...,From America's most trusted financial advisor ...,1998.0,3.62,320.0,254.0,Die Broke: A Radical Four-Part Financial Plan,9780887309427 From America's most trusted fina...
4315,9781400032389,1400032385,Letters to a Young Artist,Anna Deavere Smith,Business & Economics,http://books.google.com/books/content?id=c3t-A...,Provides advice to young artists on how they c...,2006.0,4.01,240.0,522.0,Letters to a Young Artist,9781400032389 Provides advice to young artists...
4711,9781576753514,1576753514,Managers Not MBAs,Henry Mintzberg,Business & Economics,http://books.google.com/books/content?id=VAzkS...,A professor of management studies at McGill Un...,2005.0,3.85,464.0,144.0,Managers Not MBAs: A Hard Look at the Soft Pra...,9781576753514 A professor of management studie...
4745,9781580624596,1580624596,Sun Tzu,Sun-tzu;Gerald A. Michaelson,Business & Economics,http://books.google.com/books/content?id=eUNB2...,Learn the strategic rules of Sun Tzu and how t...,2001.0,3.80,224.0,290.0,Sun Tzu: The Art of War for Managers; 50 Strat...,9781580624596 Learn the strategic rules of Sun...
4786,9781585424337,1585424331,Think and Grow Rich,Napoleon Hill;Arthur R. Pell,Business & Economics,http://books.google.com/books/content?id=HO-cn...,An updated edition of the best-selling guide f...,2005.0,4.18,320.0,88437.0,Think and Grow Rich: The Landmark Bestseller--...,9781585424337 An updated edition of the best-s...
4859,9781591391678,1591391679,Hardball,George Stalk;Robert Lachenauer;John Butman,Business & Economics,http://books.google.com/books/content?id=cscGB...,Hardball takes leaders deep inside the world o...,2004.0,3.49,192.0,82.0,Hardball: Are You Playing to Play Or Playing t...,9781591391678 Hardball takes leaders deep insi...
5050,9781857880786,1857880781,Snapshots From Hell,Peter Robinson,Business & Economics,http://books.google.com/books/content?id=Pgb8w...,This work is an attempt to provide an answer t...,2005.0,3.69,296.0,560.0,Snapshots From Hell: The Making of an MBA,9781857880786 This work is an attempt to provi...

In [5]:
    category_mapping = {'Fiction' : "Fiction",
'Juvenile Fiction': "Children's Fiction",
'Biography & Autobiography': "Nonfiction",
'History': "Nonfiction",
'Literary Criticism': "Nonfiction",
'Philosophy': "Nonfiction",
'Religion': "Nonfiction",
'Comics & Graphic Novels': "Fiction",
'Drama': "Fiction",
'Juvenile Nonfiction': "Children's Nonfiction",
'Science': "Nonfiction",
'Poetry': "Fiction"}

books["simple_categories"] = books["categories"].map(category_mapping)
books.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,NaN
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,NaN
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",NaN

In [6]:
    books[(books["simple_categories"].isna())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,NaN
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,NaN
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",NaN
5,9780006380832,0006380832,Empires of the Monsoon,Richard Hall,"Africa, East",http://books.google.com/books/content?id=MuPEQ...,Until Vasco da Gama discovered the sea-route t...,1998.0,4.41,608.0,65.0,Empires of the Monsoon: A History of the India...,9780006380832 Until Vasco da Gama discovered t...,NaN
6,9780006470229,000647022X,The Gap Into Madness,Stephen R. Donaldson,"Hyland, Morn (Fictitious character)",http://books.google.com/books/content?id=4oXav...,A new-cover reissue of the fourth book in the ...,1994.0,4.15,743.0,103.0,The Gap Into Madness: Chaos and Order,9780006470229 A new-cover reissue of the fourt...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5190,9788125026600,8125026606,Nietzsche For Beginners,Marc Sautet,NaN,http://books.google.com/books/content?id=fPIv8...,Not only does Nietzsche for Beginners delve in...,2004.0,3.26,192.0,21.0,Nietzsche For Beginners,9788125026600 Not only does Nietzsche for Begi...,NaN
5191,9788171565641,8171565646,Aspects of the Novel,E. M. Forster,English fiction,http://books.google.com/books/content?id=qWU9P...,"Forster's lively, informed originality and wit...",2004.0,3.83,141.0,10.0,Aspects of the Novel,"9788171565641 Forster's lively, informed origi...",NaN
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...,NaN
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...,NaN
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,NaN

In [7]:
    # Use a pipeline as a high-level helper
from transformers import pipeline

fiction_categories = ["Fiction","Nonfiction"]
pipe = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

In [8]:
    sequence = books.loc[books["simple_categories"]  == "Fiction", "description"].reset_index(drop=True)[0]

In [9]:
    pipe(sequence, fiction_categories)

{'sequence': 'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.',
 'labels': ['Fiction', 'Nonfiction'],
 'scores': [0.8438268899917603, 0.15617311000823975]}

In [10]:
    import numpy as np
max_index = np.argmax(pipe(sequence, fiction_categories)["scores"])
max_label = pipe(sequence, fiction_categories)["labels"][max_index]
max_label

'Fiction'

In [11]:
    def generate_predictions(sequence, categories):
    predictions = pipe(sequence, categories)
    max_index = np.argmax(predictions["scores"])
    max_label = predictions["labels"][max_index]
    return max_label

In [12]:
    from tqdm import tqdm
#cats short fot category
actual_cats = []
predicted_cats = []

for i in tqdm(range(0, 300)):
    sequence = books.loc[books["simple_categories"] == "Fiction", "description"].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ["Fiction"]

100%|██████████| 300/300 [15:19<00:00,  3.07s/it]

In [13]:
    for i in tqdm(range(0, 300)):
    sequence = books.loc[books["simple_categories"] == "Nonfiction", "description"].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ["Nonfiction"]

100%|██████████| 300/300 [13:08<00:00,  2.63s/it]

In [14]:
    predictions_df = pd.DataFrame({"actual_categories": actual_cats, "predicted_categories": predicted_cats})

In [15]:
    predictions_df.head(5)

  actual_categories predicted_categories
0           Fiction              Fiction
1           Fiction              Fiction
2           Fiction              Fiction
3           Fiction           Nonfiction
4           Fiction              Fiction

In [16]:
    #1 for true, 0 for false
predictions_df["correct_prediction"] = np.where(predictions_df["actual_categories"] == predictions_df["predicted_categories"], 1, 0)

In [17]:
    predictions_df["correct_prediction"].sum() / len(predictions_df)

np.float64(0.7783333333333333)

In [18]:
    predictionAccuracy = predictions_df["correct_prediction"].sum() / len(predictions_df) * 100
print("Accuracy of prediction is: %", predictionAccuracy)

Accuracy of prediction is: % 77.83333333333333

In [19]:
    isbns = []
predicted_cats = []

missing_cats = books.loc[books["simple_categories"].isna(), ["isbn13", "description"]].reset_index(drop=True)

In [20]:
    for i in tqdm(range(0, len(missing_cats))):
    sequence = missing_cats["description"][i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    isbns += [missing_cats["isbn13"][i]]

100%|██████████| 1454/1454 [1:01:04<00:00,  2.52s/it]

In [21]:
    missing_predicted_df = pd.DataFrame({"isbn13" : isbns, "predicted_categories": predicted_cats})

In [22]:
    missing_predicted_df.head(5)

          isbn13 predicted_categories
0  9780002261982              Fiction
1  9780006280897           Nonfiction
2  9780006280934           Nonfiction
3  9780006380832           Nonfiction
4  9780006470229              Fiction

In [23]:
    books = pd.merge(books,missing_predicted_df, on = "isbn13", how = "left")
books["simple_categories"] = np.where(books["simple_categories"].isna(), books["predicted_categories"], books["simple_categories"])
books = books.drop(columns =["predicted_categories"])

In [24]:
    books.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction

In [25]:
    books[books["categories"].str.lower().isin([
    "romance", "science fiction",
    "scifi", "fantasy",
    "horror", "mystery",
    "thriller", "comedy",
    "crime", "historical"
])]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
24,9780006513087,0006513085,Gravity,Tess Gerritsen,Science fiction,http://books.google.com/books/content?id=KI66c...,Emma Watson a research physician has been trai...,2004.0,4.04,342.0,8024.0,Gravity,9780006513087 Emma Watson a research physician...,Nonfiction
475,9780099410355,0099410354,Traitor,Matthew Woodring Stover,Science fiction,http://books.google.com/books/content?id=VbICO...,"From the depths of catastrophe, a glimmer of h...",2002.0,4.00,320.0,6765.0,Traitor,"9780099410355 From the depths of catastrophe, ...",Fiction
478,9780099422341,0099422344,Yeats is Dead!,Joseph O'Connor,Comedy,http://books.google.com/books/content?id=DrE3I...,"In aid of Amnesty International, this is a bri...",2002.0,3.39,298.0,34.0,Yeats is Dead!: A Novel by Fifteen Irish Writers,"9780099422341 In aid of Amnesty International,...",Fiction
491,9780099446729,0099446723,Blackwood Farm,Anne Rice,Horror,http://books.google.com/books/content?id=cIn8T...,"Lestat Is Back, Saviour And Demon, Presiding O...",2003.0,3.86,774.0,26145.0,Blackwood Farm,"9780099446729 Lestat Is Back, Saviour And Demo...",Fiction
1090,9780261102422,0261102427,The Silmarillion,John Ronald Reuel Tolkien,Fantasy,http://books.google.com/books/content?id=22ePu...,Tolkien's Silmarillion is the core work of the...,1999.0,3.91,384.0,253.0,The Silmarillion,9780261102422 Tolkien's Silmarillion is the co...,Fiction
1435,9780340837955,0340837950,Stranger in a Strange Land,Robert A. Heinlein,Science fiction,http://books.google.com/books/content?id=ZQhiP...,"Epic, entertaining, Stranger in a Strange Land...",2005.0,3.92,672.0,563.0,Stranger in a Strange Land,"9780340837955 Epic, entertaining, Stranger in ...",Fiction
1439,9780345251220,0345251229,Visions from Nowhere,William Arrow,Science fiction,NaN,"The first novel in the series, ""Return to the ...",1976.0,3.23,183.0,10.0,Visions from Nowhere,"9780345251220 The first novel in the series, ""...",Fiction
2845,9780575075597,0575075597,Replay,Ken Grimwood,Fantasy,http://books.google.com/books/content?id=9vmNP...,At forty-three Jeff Winston is tired of his lo...,2005.0,4.16,272.0,412.0,Replay,9780575075597 At forty-three Jeff Winston is t...,Fiction
2860,9780590254762,0590254766,"The lion, the witch and the wardrobe",Clive Staples Lewis,Fantasy,NaN,Four English school children enter the magic l...,1995.0,4.21,189.0,860.0,"The lion, the witch and the wardrobe",9780590254762 Four English school children ent...,Nonfiction
3288,9780739423851,0739423851,Wizard's Castle,Diana Wynne Jones,Fantasy,http://books.google.com/books/content?id=hB7hA...,Howl's moving castle - Eldest of three sisters...,2002.0,4.44,376.0,439.0,Wizard's Castle,9780739423851 Howl's moving castle - Eldest of...,Fiction
3289,9780739439708,0739439707,Time Quartet,Madeleine L'Engle,Science fiction,NaN,"Blending magic with quantum physics, Madeleine...",2003.0,4.35,646.0,165.0,Time Quartet,9780739439708 Blending magic with quantum phys...,Fiction
3563,9780760728505,076072850X,"20,000 Leagues Under the Sea",Jules Verne,Science fiction,NaN,Retells the adventures of a French professor a...,2002.0,3.88,394.0,135778.0,"20,000 Leagues Under the Sea",9780760728505 Retells the adventures of a Fren...,Fiction
4483,9781416502043,1416502041,The Voyage of the Jerle Shannara Trilogy,Terry Brooks,Fantasy,http://books.google.com/books/content?id=jqVsA...,When the body of a half-drowned elf is found f...,2004.0,4.26,1260.0,84.0,The Voyage of the Jerle Shannara Trilogy,9781416502043 When the body of a half-drowned ...,Fiction
4979,9781841494081,1841494089,The Darkness that Comes Before,R. Scott Bakker,Fantasy,http://books.google.com/books/content?id=BG8qG...,A score of centuries has passed since the Firs...,2005.0,3.79,638.0,317.0,The Darkness that Comes Before,9781841494081 A score of centuries has passed ...,Nonfiction
5040,9781857231359,185723135X,Use of Weapons,Iain Banks,Science fiction,NaN,The man known as Cheradenine Zakalwe was one o...,1992.0,4.19,411.0,30779.0,Use of Weapons,9781857231359 The man known as Cheradenine Zak...,Nonfiction
5057,9781857989342,1857989341,The Gods Themselves,Isaac Asimov,Science fiction,http://books.google.com/books/content?id=8ClIP...,"In the year 2100, mankind on Earth, settlers i...",2000.0,4.09,288.0,41304.0,The Gods Themselves,"9781857989342 In the year 2100, mankind on Ear...",Fiction

In [26]:
    books.to_csv("books_with_categories.csv", index=False)